version: "3.2"

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
  SingleViewApi:
    image: single-view-api
    build:
     context: .
     dockerfile: SingleViewApi/Dockerfile
     args:
     - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    depends_on:
      - cache
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
      - PATH="$PATH:/root/.dotnet/tools"
      - PERSON_API_V1=${PERSON_API_V1}
      - REDIS_HOST=cache:6379
      - CONTACT_DETAILS_API_V2=${CONTACT_DETAILS_API_V2}
      - HOUSING_SEARCH_API_V1=${HOUSING_SEARCH_API_V1}
      - JIGSAW_LOGIN_URL=${JIGSAW_LOGIN_URL}
      - NOTES_API_V2=${NOTES_API_V2}
      - ACADEMY_API_V1=${ACADEMY_API_V1}
      - ACADEMY_API_KEY=${ACADEMY_API_KEY}
      - JIGSAW_CUSTOMER_API=${JIGSAW_CUSTOMER_API}
      - JIGSAW_HOMELESSNESS_API=${JIGSAW_HOMELESSNESS_API}
      - JIGSAW_ACCOMMODATION_API=${JIGSAW_ACCOMMODATION_API}
      - EQUALITY_INFORMATION_API_V1=${EQUALITY_INFORMATION_API_V1}
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - CAUTIONARY_ALERTS_API=${CAUTIONARY_ALERTS_API}
      - TENURE_API=${TENURE_API}
      - SHARED_PLAN_URL=${SHARED_PLAN_URL}
      - SHARED_PLAN_API=${SHARED_PLAN_API}
      - X_API_KEY=${X_API_KEY}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
    links:
      - dev-database
      - cache
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  SingleViewApi-test:
    image: single-view-api-test
    build:
      context: .
      dockerfile: SingleViewApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
# TODO: If using DynamoDb remove the line above and uncomment the section below.
#      - DynamoDb_LocalMode=true
#      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
#      - AWS_REGION=eu-west-2
#      - AWS_ACCESS_KEY_ID=local
#      - AWS_SECRET_ACCESS_KEY=local
    links:
      - test-database
# TODO: If using DynamoDb remove the line above and uncomment the line below.
#      - dynamodb-database

  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env

# TODO: If using DynamoDb remove the 'test-database' section above and uncomment the lines below.
#  dynamodb-database:
#    image: amazon/dynamodb-local
#    ports:
#      - 8000:8000
