create table customer_data_sources
(
  id             integer generated by default as identity
    constraint "PK_customer_data_sources"
      primary key,
  customer_id    uuid    not null,
  data_source_id integer not null,
  source_id      text    not null
);

alter table customer_data_sources
  owner to postgres;

create index ix_customer_data_sources_id
  on customer_data_sources (id);

create index ix_customer_data_sources_customer_id
  on customer_data_sources (customer_id);

create table customers
(
  id            uuid                                   not null
    constraint "PK_customers"
      primary key,
  first_name    text                                   not null,
  last_name     text                                   not null,
  date_of_birth date                                   not null,
  ni_number     text,
  created_at    timestamp without time zone default now() not null,
  updated_at    timestamp without time zone default now() not null
);

SET TimeZone='UTC';

alter table customers
  owner to postgres;

create index ix_customers_id
  on customers (id);

create index ix_customers_first_name
  on customers (first_name);

create index ix_customers_last_name
  on customers (last_name);

create index ix_customers_date_of_birth
  on customers (date_of_birth);

create index ix_customers_ni_number
  on customers (ni_number);

create table data_sources
(
  id   integer generated by default as identity
    constraint "PK_data_sources"
      primary key,
  name text
);

alter table data_sources
  owner to postgres;

create index ix_data_sources_id
  on data_sources (id);

INSERT INTO data_sources (id, name) VALUES (1, 'PersonAPI');
INSERT INTO data_sources (id, name) VALUES (2, 'Jigsaw');
INSERT INTO data_sources (id, name) VALUES (3, 'Academy');
