create table data_sources
(
  id  integer generated by default as identity
    constraint "PK_data_sources"
      primary key,
  name text
);

alter table data_sources
  owner to postgres;

create index ix_data_sources_id
  on data_sources (id);

INSERT INTO data_sources (id, name) VALUES (1, 'PersonAPI');
INSERT INTO data_sources (id, name) VALUES (2, 'Jigsaw');
